name: Publish Website to cPanel 2.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ftp-deploy:
    name: Deploy via FTPS (cPanel)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy to cPanel via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps
          port: 21
          security: loose
          timeout: 600000
          log-level: verbose

          local-dir: ./
          server-dir: /ifatsearm26.aata.ao/

          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**/*
            **/.vscode/**/*
            **/node_modules/**/*
            **/tests/**/*
            **/.env
            **/.env.*
            README.md
            LICENSE.txt
